### ISSUE TITLE
Manual "switches" are very slow to update

### ISSUE THREAD

**Issue by TheKatkar** [krohrbaugh/tesmart-homeassistant#17]
## System Information

version | core-2024.7.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.33-haos
arch | x86_64
timezone | Europe/Paris
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1458
Downloaded Repositories | 42

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 3 août 2024 à 02:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | eu-central-1-10.ui.nabu.casa
certificate_status | ready
instance_id | 7332022bef8c4ff690218f95022def77
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.4
-- | --
update_channel | stable
supervisor_version | supervisor-2024.06.2
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 46.5 GB
disk_used | 26.3 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | kvm
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Advanced SSH & Web Terminal (18.0.0), Zigbee2MQTT (1.39.0-1), Studio Code Server (5.15.0), Home Assistant Google Drive Backup (0.112.1), MariaDB (2.7.1), Piper (1.5.0), Whisper (2.1.2), EMQX (0.6.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 6
-- | --
resources | 31
views | 27
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 25 juin 2024 à 19:49
-- | --
current_recorder_run | 3 juillet 2024 à 21:32
estimated_db_size | 625.70 MiB
database_engine | mysql
database_version | 10.11.6

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Manual switches take a long time to be updated in the integration.

### Reproduction steps

1. Press the "button 2" 
2. Wait a very long time (5 mn)
3. Source finaly Update 
...

### Debug logs

```text
...
```

### Diagnostics dump

...

**Comment by krohrbaugh** [comment]
Thanks for the issue report, @TheKatkar !

The problem here is that the TESmart devices don't broadcast device state changes. As a result, there's no persistent connection between Home Assistant (HA) and the device. The integration instead relies on HA's built-in polling mechanisms to detect device-driven state changes.

Due to this, the integration works best where no manual interaction with the device occurs, and everything is instead controlled via HA.

_However_, if that doesn't work for your scenario, there's a standard way to disable the default polling that HA manages for the integration, and setup a custom polling interval. This is [documented here](https://www.home-assistant.io/common-tasks/general#defining-a-custom-polling-interval).

I hope this helps address your issue. If I've misunderstood the problem, please let me know.

**Comment by TheKatkar** [comment]
Thanks for your reply @krohrbaugh !
It was very clear, and i learn somthing new 👍
