### ISSUE TITLE
Source status not updating when using physical buttons or keyboard shortcuts

### ISSUE THREAD

**Issue by jeroen-github** [krohrbaugh/tesmart-homeassistant#37]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

First of all thanks for this integration, it seems the selected source is not updated when using the physical buttons or when using the shortcut on the keyboard.
Am I doing something wrong ? or can this be implemented ?

### Describe the solution you'd like

Update source when using physical buttons / keyboard shortcuts

### Describe alternatives you've considered

no idea

### Additional context

NA

**Comment by krohrbaugh** [comment]
Hi there! Thanks for filing this issue.

This integration depends on polling to update the device status, because the protocol being used does not support bidirectional communication. It will update, but only at the polling frequency your Home Assistant instance is configured for.

For more information, please refer to [my comment on this issue](https://github.com/krohrbaugh/tesmart-homeassistant/issues/17#issuecomment-2211370474).

If that information addresses your request, please close this issue. Thanks!

**Comment by jeroen-github** [comment]
Thanks this answers my question
